### ISSUE TITLE
Lima fails to install on fedora 40 using homebrew

### ISSUE THREAD

**Issue by nunodio** [lima-vm/lima#2554]
### Description

Hello,

Lima fails to install on brand new installation of Linux Fedora 40 (Kernel version: 6.10.3-200.fc40.x86_64).

**Log**

```
...

==> Installing lima dependency: z3
==> Downloading https://ghcr.io/v2/homebrew/core/z3/manifests/4.13.0
Already downloaded: /home/bam/.cache/Homebrew/downloads/f76733dc8564492bde6da5ddd68bf485a259b09d276de374047a4600ed52edff--z3-4.13.0.bottle_manifest.json
==> Pouring z3--4.13.0.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/z3/4.13.0: 120 files, 42MB
==> Installing lima dependency: binutils
==> Downloading https://ghcr.io/v2/homebrew/core/binutils/manifests/2.43
Already downloaded: /home/bam/.cache/Homebrew/downloads/c086ada2e0761961442064a7ce59af44d29ee81da5fd8a8e9ed98615d3ce9c25--binutils-2.43.bottle_manifest.json
==> Pouring binutils--2.43.x86_64_linux.bottle.tar.gz
Error: no implicit conversion of false into String
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:9:in `popen_read'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/ld.rb:13:in `brewed_ld_so_diagnostics'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/ld.rb:23:in `sysconfdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/ld.rb:44:in `library_paths'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:165:in `find_full_lib_path'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:131:in `block in initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:131:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:131:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:213:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:213:in `metadata'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:222:in `dynamically_linked_libraries'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:115:in `block in check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/pathname.rb:577:in `block in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/find.rb:51:in `block (2 levels) in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/find.rb:50:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/find.rb:50:in `block in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/find.rb:45:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/find.rb:45:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/pathname.rb:577:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/forwardable.rb:240:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:108:in `check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/linkage_checker.rb:32:in `check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:32:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2910:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2910:in `block in undeclared_runtime_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cache_store.rb:26:in `use'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2909:in `undeclared_runtime_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2317:in `runtime_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:829:in `finish'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:757:in `install_dependency'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:675:in `block in install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:675:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:675:in `install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:412:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:212:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:301:in `block in install_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:300:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:300:in `install_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:300:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

**Replicate the issue:**

- Install Fedora 40

- Upgrade all the packages
`sudo dnf update -y`

- Install Development tools
`sudo dnf groupinstall "Development Tools"`

- install homebrew
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

- Install lima via brew
`brew install lima`

Thank you.

**Comment by AkihiroSuda** [comment]
This is an issue of brew, not lima

https://docs.brew.sh/Troubleshooting
